### ISSUE TITLE
request-default-error-callback

### ISSUE THREAD

**Issue by incandescentman** [junjizhi/aide.el#4]
This was working perfectly for a while, but now it's giving me "Empty result" with this error:

    [error] request--callback: peculiar error: 401
    [error] request-default-error-callback: https://api.openai.com/v1/engines/davinci/completions

I'm not sure if it's because OpenAI updated its engines/models or some other reason. Thank you!

**Comment by richardwesthaver** [comment]
@incandescentman 401 http status indicates an issue with credentials. I would check your token if you’re still having an issue
